timeout: 1200s
steps:

  - id: build
    name: gcr.io/cloud-builders/docker
    dir: builder
    args: [build, "--tag=gcr.io/${PROJECT_ID}/builder:${COMMIT_SHA}", .]
    waitFor: [pull-latest]

images: ["gcr.io/${PROJECT_ID}/builder:${COMMIT_SHA}"]
